root: ./content

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  tutorials/installation: introduction/installation.md
  integrations/programmatic-clients: reference/sql/supported-clients/clients.md
  getting-started/dolthub: concepts/dolthub/README.md
  bounties/bounties: introduction/getting-started/data-bounties.md
  reference/sql: reference/sql/server/README.md
  reference/sql/configuration: reference/sql/server/configuration.md
  reference/sql/access-management: reference/sql/server/access-management.md
  reference/sql/backups: reference/sql/server/backups.md
  reference/sql/replication: reference/sql/server/replication.md
  reference/sql/branches: reference/sql/version-control/branches.md
  reference/sql/querying-history: reference/sql/version-control/querying-history.md
  reference/sql/dolt-sql-procedures: reference/sql/version-control/dolt-sql-procedures.md
  reference/sql/dolt-sql-functions: reference/sql/version-control/dolt-sql-functions.md
  reference/sql/dolt-system-tables: reference/sql/version-control/dolt-system-tables.md
  reference/sql/dolt-sysvars: reference/sql/version-control/dolt-sysvars.md
  reference/sql/saved-queries: reference/sql/version-control/saved-queries.md
  reference/sql/sql-support: reference/sql/sql-support/README.md
  reference/sql/sql-support/data-description.md: reference/sql/sql-support/data-description.md
  reference/sql/sql-support/expressions-functions-operators.md: reference/sql/sql-support/expressions-functions-operators.md
  reference/sql/sql-support/supported-statements.md: reference/sql/sql-support/supported-statements.md
  reference/sql/sql-support/miscellaneous.md: reference/sql/sql-support/miscellaneous.md
  reference/sql/benchmarks: reference/sql/benchmarks/README.md
  reference/sql/benchmarks/correctness: reference/sql/benchmarks/correctness.md
  reference/sql/benchmarks/latency: reference/sql/benchmarks/latency.md
  reference/sql/benchmarks/imports: reference/sql/benchmarks/import.md
