root: ./content

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  guides/administrator: guides/basic.md
  guides/features: features/basic/README.md
  guides/features/api: features/advanced/api.md
  guides/features/workspaces: features/advanced/workspaces.md
  guides/features/transform-uploads: features/advanced/transform-uploads.md
  release-notes: reference/release-notes/README.md
  release-notes/2.0.0: reference/release-notes/2.0.0.md
  release-notes/2.0.1: reference/release-notes/2.0.1.md
  release-notes/2.0.2: reference/release-notes/2.0.2.md
  release-notes/2.0.3: reference/release-notes/2.0.3.md
  release-notes/2.0.4: reference/release-notes/2.0.4.md
  release-notes/2.0.5: reference/release-notes/2.0.5.md
  release-notes/2.0.6: reference/release-notes/2.0.6.md
  release-notes/2.0.7: reference/release-notes/2.0.7.md
  release-notes/2.0.8: reference/release-notes/2.0.8.md
  release-notes/2.1.0: reference/release-notes/2.1.0.md
  release-notes/2.1.1: reference/release-notes/2.1.1.md
  release-notes/2.1.2: reference/release-notes/2.1.2.md
  release-notes/2.1.3: reference/release-notes/2.1.3.md
  release-notes/2.1.4: reference/release-notes/2.1.4.md
  release-notes/2.1.5: reference/release-notes/2.1.5.md
