root: ./content

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  tutorials/installation: introduction/installation.md
  integrations/programmatic-clients: reference/sql/supported-clients/clients.md
  getting-started/dolthub: concepts/dolthub/README.md
  introduction/getting-started/data-sharing: products/dolthub/data-sharing.md
  reference/sql: reference/sql/server/README.md
  reference/sql/configuration: reference/sql/server/configuration.md
  reference/sql/access-management: reference/sql/server/access-management.md
  reference/sql/backups: reference/sql/server/backups.md
  reference/sql/replication: reference/sql/server/replication.md
  reference/sql/branches: reference/sql/version-control/branches.md
  reference/sql/querying-history: reference/sql/version-control/querying-history.md
  reference/sql/dolt-sql-procedures: reference/sql/version-control/dolt-sql-procedures.md
  reference/sql/dolt-sql-functions: reference/sql/version-control/dolt-sql-functions.md
  reference/sql/dolt-system-tables: reference/sql/version-control/dolt-system-tables.md
  reference/sql/dolt-sysvars: reference/sql/version-control/dolt-sysvars.md
  reference/sql/saved-queries: reference/sql/version-control/saved-queries.md
  reference/sql/sql-support: reference/sql/sql-support/README.md
  reference/sql/sql-support/data-description.md: reference/sql/sql-support/data-description.md
  reference/sql/sql-support/expressions-functions-operators.md: reference/sql/sql-support/expressions-functions-operators.md
  reference/sql/sql-support/supported-statements.md: reference/sql/sql-support/supported-statements.md
  reference/sql/sql-support/miscellaneous.md: reference/sql/sql-support/miscellaneous.md
  reference/sql/benchmarks: reference/sql/benchmarks/README.md
  reference/sql/benchmarks/correctness: reference/sql/benchmarks/correctness.md
  reference/sql/benchmarks/latency: reference/sql/benchmarks/latency.md
  reference/sql/benchmarks/import: reference/sql/benchmarks/import.md
  concepts/dolthub/api: products/dolthub/dolthub-api/README.md
  concepts/dolthub/hooks: products/dolthub/dolthub-api/hooks.md
  guides/dolthub-api/: products/dolthub/dolthub-api/README.md
  guides/dolthub-api/hooks: products/dolthub/dolthub-api/hooks.md
  guides/dolthub-api/authentication: products/dolthub/dolthub-api/authentication.md
  guides/dolthub-api/csv: products/dolthub/dolthub-api/csv.md
  guides/dolthub-api/database: products/dolthub/dolthub-api/database.md
  guides/dolthub-api/sql: products/dolthub/dolthub-api/sql.md
  guides/doltlab/: products/doltlab/README.md
  guides/doltlab/installation: products/doltlab/README.md
  guides/doltlab/administrator: products/doltlab/README.md
  products/doltlab/installation: products/doltlab/README.md
  products/doltlab/administrator: products/doltlab/README.md
  products/doltlab/api: products/doltlab/README.md
  products/doltgres/installation: products/doltgres/README.md
  products/doltgres/replication-from-postgres: products/doltgres/README.md
  products/doltgres/running-server: products/doltgres/README.md